var arg_skill=argument0
switch floor(arg_skill){
    case 1: return "rest" 
    case 2: return "laser beam" 
    case 3: return "water breath" 
    case 4: return "bite" 
    case 5: return "redemptioN"
    case 6: return "split"
    case 7: return "pierciNg strike"
    case 8: return "fire"
    case 9: return "heal"
    case 10: return "cross slash"
    case 11: return "loNg shot"
    case 12: return "swap"
    case 13: return "barrier"
    case 14: return "spirit bow"
    case 15: return "ice"
    case 16: return "thuNder"
    case 17: return "wiNd"
    case 18: return "glutuNy"
    case 19: return "flux"
    case 20: return "coNsume"
    case -1: return "spawn vine start"
    case -2: return "spawn vine"
    default:return""
}
