var arg_item=argument0
switch floor(arg_item){
    case 1: return "Juice Box "+string(round(frac(arg_item)*100))+"" 
    case 2: return "Dagger "//+string(round(frac(arg_item)*100))+"" 
    case 3: return "First Aid "//+string(round(frac(arg_item)*100))+"" 
    case 4: return "Screwdriver "+string(round(frac(arg_item)*100))+"" 
    case 5: return "Hotdog "+string(round(frac(arg_item)*100))+"" 
    case 6: return "Rock "//+string(round(frac(arg_item)*100))+"" 
    case 7: return "Bow "//+string(round(frac(arg_item)*100))+"" 
    case 8: return "Sword "//+string(round(frac(arg_item)*100))+"" 
    case 9: return "Club "//+string(round(frac(arg_item)*100))+"" 
    case 10: return "Stick "//+string(round(frac(arg_item)*100))+"" 
    case 11: return "Spiritbow "//+string(round(frac(arg_item)*100))+"" 
    case 12: return "Iron Sword "//+string(round(frac(arg_item)*100))+"" 
    case 13: return "Kranbit "//+string(round(frac(arg_item)*100))+"" 
    case 14: return "Great Sword "//+string(round(frac(arg_item)*100))+"" 
    case 15: return "Great Bow "//+string(round(frac(arg_item)*100))+"" 
    case 16: return "Cross Bow "//+string(round(frac(arg_item)*100))+"" 
    case 17: return "Spear "//+string(round(frac(arg_item)*100))+"" 
    case 18: return "Shurikin "//+string(round(frac(arg_item)*100))+"" 
    case 19: return "Battle Axe "//+string(round(frac(arg_item)*100))+"" 
    case 20: return "Gael Bolg "//+string(round(frac(arg_item)*100))+"" 
    case 21: return "Axe "//+string(round(frac(arg_item)*100))+"" 
    case 22: return "Herb "+string(round(frac(arg_item)*100))+"" 
    case 50: return "Xcalabur "//+string(round(frac(arg_item)*100))+"" 
    case 51: return "Aegis ??"//+string(round(frac(arg_item)*100))+"" 
    default:return""
}
