var arg_item=argument0
switch floor(arg_item){
    case 1: return "juice box "+string(round(frac(arg_item)*100))+"" 
    case 2: return "dagger "+string(round(frac(arg_item)*100))+"" 
    case 3: return "first aid "+string(round(frac(arg_item)*100))+"" 
    case 4: return "screwdriver "+string(round(frac(arg_item)*100))+"" 
    case 5: return "hotdog "+string(round(frac(arg_item)*100))+"" 
    case 6: return "rock "+string(round(frac(arg_item)*100))+"" 
    case 7: return "bow "+string(round(frac(arg_item)*100))+"" 
    case 8: return "sword "+string(round(frac(arg_item)*100))+"" 
    case 9: return "club "+string(round(frac(arg_item)*100))+"" 
    case 10: return "stick "+string(round(frac(arg_item)*100))+"" 
    case 11: return "spiritbow "+string(round(frac(arg_item)*100))+"" 
    case 12: return "iroN sword "+string(round(frac(arg_item)*100))+"" 
    case 13: return "kraNbit "+string(round(frac(arg_item)*100))+"" 
    case 14: return "great sword "+string(round(frac(arg_item)*100))+"" 
    case 15: return "great bow "+string(round(frac(arg_item)*100))+"" 
    case 16: return "cross bow "+string(round(frac(arg_item)*100))+"" 
    case 17: return "spear "+string(round(frac(arg_item)*100))+"" 
    case 18: return "shurikiN "+string(round(frac(arg_item)*100))+"" 
    case 19: return "battle axe "+string(round(frac(arg_item)*100))+"" 
    case 20: return "gael bolg "+string(round(frac(arg_item)*100))+"" 
    case 21: return "axe "+string(round(frac(arg_item)*100))+"" 
    case 22: return "herb "+string(round(frac(arg_item)*100))+"" 
    case 50: return "xcalabur "+string(round(frac(arg_item)*100))+"" 
    case 51: return "aegis ??"//+string(round(frac(arg_item)*100))+"" 
    default:return""
}
