var arg_skill=argument0
switch floor(arg_skill){
    case 1: return "Rest" 
    case 2: return "Laser Beam" 
    case 3: return "Water Breath" 
    case 4: return "Bite" 
    case 5: return "Redemption"
    case 6: return "Split"
    case 7: return "Piercing Strike"
    case 8: return "Fire"
    case 9: return "Heal"
    case 10: return "Cross Slash"
    case 11: return "Long shot"
    case 12: return "Swap"
    case 13: return "Barrier"
    case 14: return "Spirit Bow"
    case 15: return "Ice"
    case 16: return "Thunder"
    case 17: return "Wind"
    case 18: return "Glutuny"
    case 19: return "Flux"
    case 20: return "Consume"
    case 21: return "Blessing"
    //case 22: return "bash"
    case -1: return "spawn vine start"
    case -2: return "spawn vine"
    default:return""
}
